version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install:ci
      - save_cache:
          name: Save Yarn Package Cache
          key: root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/repo
          paths: ./node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint
          command: yarn lint

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build packages
          command: yarn build

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run unit tests
          command: yarn test:ci

workflows:
  version: 2
  install-build-and-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
#      - build:
#          requires:
#            - lint
#      - test:
#          requires:
#            - build
