var_1: &cache_key ng-qt-yarn-{{ checksum "yarn.lock" }}-{{ checksum "WORKSPACE" }}

var_2: &job_defaults
  working_directory: ~/ng-qt
  docker:
    - image: ngqt/qode

var_3: &yarn_install
  run:
    name: Running Yarn install
    command: yarn install:ci

var_4: &setup_circleci_bazel_config
  run:
    name: Setting up CircleCI bazel configuration
    command: |
      cp .circleci/bazel.linux.rc $HOME/.bazelrc

var_5: &restore_cache
  restore_cache:
    keys:
      - *cache_key

var_6: &publish_branches_filter
  branches:
    only:
      - master

var_7: &attach_workspace
  attach_workspace:
    at: ~/

version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  setup:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_cache
      - *yarn_install
      # Make the bazel directories and add a file to them if they don't exist already so that
      # persist_to_workspace does not fail.
      - run:
          name: Ensure Bazel repository cache
          command: |
            if [ ! -d ~/bazel_repository_cache ]; then
              mkdir ~/bazel_repository_cache
              touch ~/bazel_repository_cache/MARKER
            fi
      # Persist any changes at this point to be reused by further jobs.
      # **NOTE 1 **: Folders persisted here should be kept in sync with `var_13: &attach_workspace`.
      # **NOTE 2 **: To add new content to the workspace, always persist on the same root.
      - persist_to_workspace:
          root: ~/
          paths:
            - ./ng-qt
            - ./bazel_repository_cache

  checks:
    <<: *job_defaults
    steps:
      - *attach_workspace
      - run:
          name: Running shellcheck
          command: |
            apt update
            apt install shellcheck
            shellcheck scripts/*.sh
      - run:
          name: Codechecks
          command: yarn codechecks

  lint:
    <<: *job_defaults
    steps:
      - *attach_workspace
      - run:
          name: Lint
          command: yarn lint

  build:
    <<: *job_defaults
    steps:
      - checkout
      - *attach_workspace
      - *setup_circleci_bazel_config
      - run: ./scripts/build-packages-dist.sh
      # Save the npm packages from //packages/... for other workflow jobs to read
      - persist_to_workspace:
          root: ~/
          paths:
            - ./ng-qt/dist
      # Save dependencies and bazel repository cache to use on subsequent runs.
      - save_cache:
          key: *cache_key
          paths:
            - node_modules
            - ~/bazel_repository_cache
  test:
    <<: *job_defaults
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Run unit tests
          command: yarn test:ci
      - codecov/upload:
          file: ./coverage/coverage-final.json
  publish:
    <<: *job_defaults
    steps:
      - checkout
      - *attach_workspace

workflows:
  version: 2
  default_workflow:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - checks:
          requires:
            - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - build
      - publish:
          filters:
            <<: *publish_branches_filter
          requires:
            - checks
            - test
            - lint
            - build
