var_1: &default_docker_image circleci/node:12

var_2: &cache_key ng-qt-yarn-{{ checksum "yarn.lock" }}-{{ checksum "WORKSPACE" }}

var_3: &job_defaults
  working_directory: ~/ng-qt
  docker:
    - image: *default_docker_image

var_4: &yarn_install
  run:
    name: Running Yarn install
    command: yarn install:ci

var_5: &setup_circleci_bazel_config
  run:
    name: Setting up CircleCI bazel configuration
    command: |
      sudo cp .circleci/bazel.linux.rc $HOME/.bazelrc

var_6: &restore_cache
  restore_cache:
    keys:
      - *cache_key

var_7: &publish_branches_filter
  branches:
    only:
      - master

var_8: &attach_workspace
  attach_workspace:
    at: ~/

version: 2
jobs:
  setup:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_cache
      - *yarn_install
      # Make the bazel directories and add a file to them if they don't exist already so that
      # persist_to_workspace does not fail.
      - run:
          name: Ensure Bazel repository cache
          command: |
            if [ ! -d ~/bazel_repository_cache ]; then
              mkdir ~/bazel_repository_cache
              touch ~/bazel_repository_cache/MARKER
            fi
      - run:
          name: Fix qode permissions
          command: |
            sudo chmod -R 777 node_modules/@nodegui/qode
      # Persist any changes at this point to be reused by further jobs.
      # **NOTE 1 **: Folders persisted here should be kept in sync with `var_13: &attach_workspace`.
      # **NOTE 2 **: To add new content to the workspace, always persist on the same root.
      - persist_to_workspace:
          root: ~/
          paths:
            - ./ng-qt
            - ./bazel_repository_cache

  lint:
    <<: *job_defaults
    steps:
      - *attach_workspace
      - run:
          name: Running shellcheck
          command: |
            sudo apt install shellcheck
            shellcheck scripts/*.sh
      - run:
          name: Lint
          command: yarn lint

  build:
    <<: *job_defaults
    steps:
      - checkout
      - *attach_workspace
      - *setup_circleci_bazel_config

      - run: ./scripts/build-packages-dist.sh

      # Save the npm packages from //packages/... for other workflow jobs to read
      - persist_to_workspace:
          root: ~/
          paths:
            - ./ng-qt/dist
      # Save dependencies and bazel repository cache to use on subsequent runs.
      - save_cache:
          key: *cache_key
          paths:
            - node_modules
            - ~/bazel_repository_cache
  test:
    <<: *job_defaults
    steps:
      - checkout
      - *attach_workspace
      # - *setup_circleci_bazel_config
      - run:
          name: Run unit tests
          command: yarn test:ci

  publish:
    <<: *job_defaults
    steps:
      - checkout
      - *attach_workspace

workflows:
  version: 2
  default_workflow:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
      - publish:
          filters:
            <<: *publish_branches_filter
          requires:
            - test
            - lint
            - build
