version: 2.1

orbs:
  node: circleci/node@1.1

defaults: &defaults
  working_directory: ~/workspace
  executor:
    name: node/default
    tag: 12.9.1

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install dependencies
                command: yarn install:ci

  lint:
    <<: *defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Lint project
                command: yarn lint

  build:
    <<: *defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Build packages
                command: yarn build

  test:
    <<: *defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Run unit tests
                command: yarn test:ci

workflows:
  version: 2
  install-build-and-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
