name: 'NG-QT workflow'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          yarn install:ci

  build:
    name: Build packages
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          yarn build

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          yarn test:ci
